cta:
  left:
    title: Chci koupit tuto službu
    description:  Líbí se Vám tento produkt, neváhejte nás kontaktovat a probereme možnosti.
    button: Zjistit více
  right:
    title: Chci se stát členem
    description: Líbí se Vám tento produkt a chtěli byste se podílet na jeho směřování?
    button: Zjistit více
