cta:
  left:
    title: Chci řešení na míru
    description:  Lorem ipsum je označení pro standardní pseudolatinský text užívaný v grafickém designu.
    button: Zjistit více
  right:
    title: Chci se stát členem
    description: Lorem ipsum je označení pro standardní pseudolatinský text užívaný v grafickém designu.
    button: Zjistit více
